variable "cloud_run_name" {

  description = "Name must be unique within a namespace, within a Cloud Run region. Is required when creating resources. Name is primarily intended for creation idempotence and configuration definition."
  type        = string
  default     = ""
}

variable "cloud_run_location" {

  description = "The location of the cloud run instance. eg us-central1"
  type        = string
  default     = ""
}


variable "cloud_run_traffic_revision_name" {

  description = "Optional metadata for this Revision, including labels and annotations. Name will be generated by the Configuration. RevisionSpec holds the desired state of the Revision."
  type        = string
  default     = ""
}

variable "cloud_run_traffic_percent" {
  description = "Percent specifies percent of the traffic to this Revision or Configuration."
  type        = number
  default     = 0

}

variable "cloud_run_traffic_latest_revision" {
  description = "LatestRevision may be optionally provided to indicate that the latest ready Revision of the Configuration should be used for this traffic target."
  type        = bool
  default     = false

}

variable "cloud_run_template_metadata_labels" {
  description = "Map of string keys and values that can be used to organize and categorize (scope and select) objects."
  type        = map(string)
  default     = {}

}

variable "cloud_run_template_metadata_generartion" {
  description = "A sequence number representing a specific generation of the desired state."
  type        = string
  default     = ""

}

variable "cloud_run_template_metadata_resource_version" {
  description = "An opaque value that represents the internal version of this object that can be used by clients to determine when objects have changed. "
  type        = string
  default     = ""

}

variable "cloud_run_template_metadata_self_link" {
  description = "SelfLink is a URL representing this object."
  type        = string
  default     = ""

}

variable "cloud_run_template_metadata_uid" {
  description = "UID is a unique id generated by the server on successful creation of a resource and is not allowed to change on PUT operations."
  type        = string
  default     = ""

}

variable "cloud_run_template_metadata_namespace" {
  description = "In Cloud Run the namespace must be equal to either the project ID or project number."
  type        = string
  default     = ""

}

variable "cloud_run_template_metadata_annotations" {
  description = "Annotations is a key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata."
  type        = map(string)
  default     = {}

}

variable "cloud_run_template_metadata_name" {
  description = "Name must be unique within a namespace, within a Cloud Run region. Is required when creating resources."
  type        = string
  default     = ""

}

variable "cloud_run_template_spec_containers_working_dir" {
  description = "Container's working directory."
  type        = string
  default     = ""

}

variable "cloud_run_template_spec_containers_args" {
  description = "Arguments to the entrypoint."
  type        = list(string)
  default     = []

}

variable "cloud_run_template_spec_containers_env_from_prefix" {
  description = "An optional identifier to prepend to each key in the ConfigMap."
  type        = string
  default     = ""

}

variable "cloud_run_template_spec_containers_env_from_config_map_ref_optional" {
  description = "Specify whether the ConfigMap must be defined"
  type        = string
  default     = ""

}

variable "cloud_run_template_spec_containers_env_from_config_map_ref_local_object_reference_name" {
  description = "The ConfigMap to select from. "
  type        = string
  default     = ""

}

variable "cloud_run_template_spec_containers_env_from_secret_ref_local_object_reference_name" {
  description = " Name of the referent.  "
  type        = string
  default     = ""

}

variable "cloud_run_template_spec_containers_env_from_secret_ref_optional" {
  description = "Specify whether the Secret must be defined"
  type        = string
  default     = ""

}

variable "cloud_run_template_spec_containers_image" {
  description = "Docker image name."
  type        = string
  default     = ""

}

variable "cloud_run_template_spec_containers_command" {
  description = "Entrypoint array. "
  type        = list(string)
  default     = []

}

variable "cloud_run_template_spec_containers_env_name" {
  description = "Name of the environment variable."
  type        = string
  default     = ""

}

variable "cloud_run_template_spec_containers_env_value" {
  description = "Variable references $(VAR_NAME) are expanded using the previous defined environment variables in the container and any route environment variables."
  type        = string
  default     = ""

}

variable "cloud_run_template_spec_containers_env_value_from_secret_key_ref_key" {
  description = " A Cloud Secret Manager secret version."
  type        = string
  default     = ""

}

variable "cloud_run_template_spec_conatainers_env_value_from_secret_key_ref_name" {
  description = " The name of the secret in Cloud Secret Manager. "
  type        = string
  default     = ""

}

variable "cloud_run_template_spec_containers_ports_name" {
  description = "Name of the port."
  type        = string
  default     = ""

}

variable "cloud_run_template_spec_containers_ports_protocol" {
  description = " Protocol used on port. Defaults to TCP."
  type        = string
  default     = ""

}

variable "cloud_run_template_spec_contaiiners_ports_container_port" {
  description = "Port number."
  type        = string
  default     = ""

}

variable "cloud_run_template_spec_containers_resources_limits" {
  description = "Limits describes the maximum amount of compute resources allowed. "
  type        = map(string)
  default     = {}

}

variable "cloud_run_template_spec_containers_resources_requests" {
  description = " Requests describes the minimum amount of compute resources required."
  type        = map(string)
  default     = {}

}



variable "cloud_run_template_spec_container_concurrency" {
  description = "ContainerConcurrency specifies the maximum allowed in-flight (concurrent) requests per container of the Revision."
  type        = string
  default     = ""

}

variable "cloud_run_template_spec_timeout_seconds" {
  description = " TimeoutSeconds holds the max duration the instance is allowed for responding to a request."
  type        = string
  default     = ""

}

variable "cloud_run_template_spec_service_account_name" {
  description = " Email address of the IAM service account associated with the revision of the service."
  type        = string
  default     = ""

}


variable "cloud_run_template_spec_serving_state" {
  description = "ServingState holds a value describing the state the resources are in for this Revision. "
  type        = string
  default     = ""

}



